# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='contato_telefone',
            field=models.CharField(default=-3, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='contato_estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viuvo')], max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='contato_sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=50, verbose_name='Sexo'),
        ),
    ]
